name: My first CI

description: My first CI

on:
  pull_request:
   branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  first_job:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v4
      - name: print hello world
        run: echo Hello, world!
      - name: date show
        run: echo $(date)

  second__job:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v4
      - name: print current user
        run: echo $(whoami)
      - name: List files in the workspace
        run: ls -la
        
